apiVersion: v1
kind: Service
metadata:
  name: aegis-error-generator
  namespace: aegis-simulation
  labels:
    app: aegis-error-generator
    component: client-simulation
spec:
  type: ClusterIP
  selector:
    app: aegis-error-generator
  ports:
    - name: http
      port: 80
      targetPort: http
