apiVersion: v1
kind: Namespace
metadata:
  name: aegis-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-api
  namespace: aegis-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-api
  template:
    metadata:
      labels:
        app: java-api
    spec:
      containers:
        - name: java-api
          image: europe-central2-docker.pkg.dev/aegis-client-420/aegis-client-services/aegis-client-java-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SERVICE_NAME
              value: java-api
            - name: CLIENT_PROJECT_ID
              value: "aegis-client-420"
            - name: ENVIRONMENT
              value: dev
            - name: CHAOS_ENABLED
              value: "true"
            - name: CHAOS_AUTO_MODE
              value: "true"
            - name: CHAOS_AUTO_INTERVAL_SECONDS
              value: "120"
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8080
            initialDelaySeconds: 25
---
apiVersion: v1
kind: Service
metadata:
  name: java-api
  namespace: aegis-demo
spec:
  selector:
    app: java-api
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: aegis-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: europe-central2-docker.pkg.dev/aegis-client-420/aegis-client-services/aegis-client-python-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: SERVICE_NAME
              value: python-api
            - name: CLIENT_PROJECT_ID
              value: "aegis-client-420"
            - name: ENVIRONMENT
              value: dev
            - name: CHAOS_ENABLED
              value: "true"
            - name: CHAOS_AUTO_MODE
              value: "true"
            - name: CHAOS_AUTO_INTERVAL_SECONDS
              value: "120"
            - name: JAVA_API_BASE_URL
              value: http://java-api:8080
          readinessProbe:
            httpGet:
              path: /healthz/ready
              port: 8000
            initialDelaySeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: python-api
  namespace: aegis-demo
spec:
  selector:
    app: python-api
  ports:
    - port: 8000
      targetPort: 8000