spring:
  application:
    name: java-api

server:
  port: 8080

aegis:
  service-name: ${SERVICE_NAME:java-api}
  client-project-id: ${CLIENT_PROJECT_ID:aegis-client-420}
  environment: ${ENVIRONMENT:local}
  team: ${TEAM:demo}
  version: ${APP_VERSION:0.1.0}
  chaos-enabled: ${CHAOS_ENABLED:true}
  chaos-max-slow-seconds: ${CHAOS_MAX_SLOW_SECONDS:30}
  chaos-max-pricing-5xx-seconds: ${CHAOS_MAX_PRICING_5XX_SECONDS:300}
